# Generated by Django 4.2.7 on 2023-11-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('text', models.TextField(verbose_name='text')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='article/', verbose_name='article_image')),
                ('data_created', models.DateField(default='2023-01-01', verbose_name='Data created')),
                ('data_published', models.DateField(default='2023-01-01', verbose_name='Data published')),
                ('number_views', models.IntegerField(verbose_name='number of views')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
