# Generated by Django 4.2.7 on 2023-11-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_created',
            field=models.DateField(default='2023-01-01', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_last_change',
            field=models.DateField(default='2023-01-01', verbose_name='Дата последнего изменения'),
        ),
    ]
