# Generated by Django 4.2.7 on 2023-12-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('number_version', 'product')},
        ),
    ]
